name: Auto Pull Request

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Create Pull Request
        id: pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.ref_name }}
          destination_branch: main
          pr_title: "Auto PR: ${{ github.ref_name }} -> main"
          pr_body: "Yeni commitler ${{ github.ref_name }} branşından main branşına otomatik olarak taşındı."
          pr_reviewer: "berkayklnc"

      - name: PR created
        if: steps.pr.outputs.pull_request_number
        run: echo "PR #${{ steps.pr.outputs.pull_request_number }} created."
